### ISSUE TITLE
Problems with opening activity from StoryDisplayFragment

### ISSUE THREAD

**Issue by Jack29913** [c2mInc/C2MStoryViewer#6]
Hello,
I want to open an activity while watching stories (ie. opening ProfileActivity by clicking user picture). Problem is it's working fine when clicked item is image but if its video item story viewer acts weird on coming back. It jumps to next item, when you click left-most part (back) it doesn't go back and sometimes it just crashes. I am thinking there is a bug at onPause and onResume. How can I make it work? Thanks in advance.

```
    Process: com.c2m.storyviewer, PID: 1319
    java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.c2m.storyviewer.customview.StoriesProgressView.getProgressWithIndex(StoriesProgressView.kt:177)
        at com.c2m.storyviewer.screen.StoryDisplayFragment$initializePlayer$1.onLoadingChanged(StoryDisplayFragment.kt:205)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$3$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:807)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$fF_DLlYcEfUJHZvcXb6sZ7mP-W4.invokeListener(lambda)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:165)
```

**Comment by Jack29913** [comment]
I solved it by saving the counter before starting activity. Now it restarts from that item on return.
savePosition(counter)
